#!/usr/bin/env bash
set -euo pipefail
#
# make-app.sh — package agy-monitor as a minimal macOS .app so it opens like a native
# app instead of a browser tab. The app is a thin launcher: it makes sure the server is
# up (reusing the launchd daemon if installed, else starting a detached node), then opens
# http://127.0.0.1:$PORT as a chromeless app window in Chrome/Edge/Brave/Chromium.
#
# macOS-only. This produces a generated artifact (no backup needed — just rebuild).
#
# Usage:
#   scripts/make-app.sh [dest-dir]      # default dest: ~/Applications
#   PORT=9000 scripts/make-app.sh       # bake a non-default port into the app
#
# The app has the repo path baked in, so if you MOVE the repo you must re-run this script.

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEFAULT_DEST="$HOME/Applications"
APP_NAME="Agy Monitor"
PORT="${PORT:-8719}"
LABEL="${AGY_MONITOR_LABEL:-com.$(whoami).agy-monitor}"
BUNDLE_ID="$LABEL.app"
MIN_MACOS="11.0"
MAKE_ICON="$REPO_DIR/scripts/make-icon.js"

# ---------------------------------------------------------------------------
# Preconditions
# ---------------------------------------------------------------------------

require_macos() {
  if [ "$(uname -s)" != "Darwin" ]; then
    echo "Error: make-app.sh builds a macOS .app bundle and only runs on macOS (Darwin)." >&2
    exit 1
  fi
}

# ---------------------------------------------------------------------------
# Bundle assembly
# ---------------------------------------------------------------------------

# Rebuild-safe removal: only ever rm an existing bundle that is verifiably an app bundle.
remove_existing() {
  local app_path="$1"
  [ -e "$app_path" ] || return 0
  if [ -f "$app_path/Contents/Info.plist" ]; then
    rm -rf "$app_path"
  else
    echo "Error: $app_path exists but is not an app bundle (no Contents/Info.plist); refusing to remove it." >&2
    exit 1
  fi
}

# Generate Contents/MacOS/launcher with REPO_DIR/PORT/LABEL baked in as literals.
write_launcher() {
  local launcher="$1"
  {
    printf '#!/usr/bin/env bash\n'
    printf 'set -uo pipefail\n'
    printf '# Generated by make-app.sh — do not edit; re-run make-app.sh to regenerate.\n'
    printf 'REPO_DIR=%q\n' "$REPO_DIR"
    printf 'PORT=%q\n' "$PORT"
    printf 'LABEL=%q\n' "$LABEL"
    cat <<'LAUNCHER_BODY'
URL="http://127.0.0.1:$PORT"
LOG="$HOME/Library/Logs/agy-monitor.log"

# Finder-launched apps get a minimal PATH, so resolve node at LAUNCH time.
resolve_node() {
  local n
  n="$(command -v node 2>/dev/null || true)"
  [ -n "$n" ] && { printf '%s' "$n"; return 0; }
  for cand in /opt/homebrew/bin/node /usr/local/bin/node "$HOME/.local/bin/node"; do
    [ -x "$cand" ] && { printf '%s' "$cand"; return 0; }
  done
  return 1
}

health_ok() { curl -fsS -m 2 "$URL/api/health" >/dev/null 2>&1; }

start_server() {
  # Prefer the installed launchd daemon; else start a detached node process.
  if [ -f "$HOME/Library/LaunchAgents/$LABEL.plist" ]; then
    launchctl kickstart "gui/$(id -u)/$LABEL" >/dev/null 2>&1 || true
    return 0
  fi
  local node
  if ! node="$(resolve_node)"; then
    osascript -e 'display notification "node not found — install Node.js >= 20 from nodejs.org" with title "Agy Monitor"' >/dev/null 2>&1 || true
    return 1
  fi
  mkdir -p "$HOME/Library/Logs"
  PORT="$PORT" nohup "$node" "$REPO_DIR/server.js" >> "$LOG" 2>&1 &
}

open_app_window() {
  local browser=""
  for b in "Google Chrome" "Microsoft Edge" "Brave Browser" "Chromium"; do
    if [ -d "/Applications/$b.app" ] || [ -d "$HOME/Applications/$b.app" ]; then browser="$b"; break; fi
  done
  if [ -n "$browser" ]; then
    open -na "$browser" --args --app="$URL"
  else
    open "$URL"
  fi
}

# 1. Already healthy? Go straight to opening the window.
if ! health_ok; then
  start_server
  # Wait up to 15s (0.5s polls) for health.
  ok=0
  for _ in $(seq 1 30); do
    if health_ok; then ok=1; break; fi
    sleep 0.5
  done
  if [ "$ok" -ne 1 ]; then
    osascript -e 'display notification "agy-monitor failed to start — check ~/Library/Logs/agy-monitor.log" with title "Agy Monitor"' >/dev/null 2>&1 || true
    open -a Console "$LOG" >/dev/null 2>&1 || true
    exit 1
  fi
fi

open_app_window
LAUNCHER_BODY
  } > "$launcher"
  chmod +x "$launcher"
}

# Build the app icon into Contents/Resources/app.icns. Echoes "app" on success (the value
# for CFBundleIconFile) or nothing on failure — a missing icon must not abort the build.
build_icon() {
  local resources_dir="$1"
  [ -f "$MAKE_ICON" ] || return 0
  command -v iconutil >/dev/null 2>&1 || return 0
  command -v node >/dev/null 2>&1 || return 0
  # iconutil requires the source directory name to end in ".iconset".
  local tmpdir iconset
  tmpdir="$(mktemp -d)"
  iconset="$tmpdir/agy-monitor.iconset"
  mkdir -p "$iconset"
  if node "$MAKE_ICON" "$iconset" >/dev/null 2>&1 \
     && iconutil -c icns "$iconset" -o "$resources_dir/app.icns" >/dev/null 2>&1 \
     && [ -s "$resources_dir/app.icns" ]; then
    rm -rf "$tmpdir"
    printf 'app'
  else
    rm -rf "$tmpdir"
    return 0
  fi
}

build_app() {
  local dest="$1"
  local app_path="$dest/$APP_NAME.app"
  local contents="$app_path/Contents"
  local macos_dir="$contents/MacOS"
  local resources_dir="$contents/Resources"

  local version
  version="$(node -p 'require(process.argv[1]).version' "$REPO_DIR/package.json" 2>/dev/null || echo "0.0.0")"

  mkdir -p "$dest"
  remove_existing "$app_path"
  mkdir -p "$macos_dir" "$resources_dir"

  write_launcher "$macos_dir/launcher"

  local icon_file
  icon_file="$(build_icon "$resources_dir")"
  local icon_key=""
  if [ -n "$icon_file" ]; then
    icon_key="  <key>CFBundleIconFile</key><string>$icon_file</string>"
  else
    echo "! icon build skipped — app will use the default macOS icon." >&2
  fi

  cat > "$contents/Info.plist" <<PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>$APP_NAME</string>
  <key>CFBundleDisplayName</key><string>$APP_NAME</string>
  <key>CFBundleIdentifier</key><string>$BUNDLE_ID</string>
  <key>CFBundleExecutable</key><string>launcher</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
  <key>CFBundleShortVersionString</key><string>$version</string>
  <key>CFBundleVersion</key><string>$version</string>
  <key>LSMinimumSystemVersion</key><string>$MIN_MACOS</string>
$icon_key
</dict>
</plist>
PLIST_EOF

  echo
  echo "✓ built $app_path  (version $version, port $PORT)"
  echo "  Note: the repo path is baked into the app. If you MOVE the repo, re-run scripts/make-app.sh."
}

usage() {
  cat <<USAGE
Usage: scripts/make-app.sh [dest-dir]

Builds "$APP_NAME.app" (default dest: $DEFAULT_DEST).
  PORT=<port>   bake a non-default port (current: $PORT)
USAGE
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

main() {
  local dest
  case "${1:-}" in
    -h|--help)
      usage
      exit 0
      ;;
    *)
      dest="${1:-$DEFAULT_DEST}"
      ;;
  esac

  require_macos
  build_app "$dest"
}

main "$@"
